version: "3.9"

services:
 jupyter:
    container_name: jupyter-pyspark
    image: jupyter/pyspark-notebook:spark-3.2.0
    ports:
        - "8888:8888"
    volumes:
        - type: bind
          source: "workspace"
          target: "/home/jovyan/work"
 postgres:
    container_name: postgres
    image: postgres:latest
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
        - "5432:5432"
    volumes:
        - postgres-data:/var/lib/postgresql/data
        - ./postgres-init/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres-data:
